/**
 * skylark-bs-swt - The skylark bootstrap standard widget tookit
 * @author Hudaokeji, Inc.
 * @version v0.9.0-beta
 * @link https://github.com/skylarkui/skylark-bs-swt/
 * @license MIT
 */
define(["skylark-utils/langx","skylark-utils/browser","skylark-utils/eventer","skylark-utils/noder","skylark-utils/geom","skylark-utils/velm","skylark-utils/query","./sbswt"],function(t,i,e,s,n,f,o,a){"use strict";function h(t){return this.each(function(){var i=o(this),e=i.data("bs.affix"),s="object"==typeof t&&t;e||i.data("bs.affix",e=new r(this,s)),"string"==typeof t&&e[t]()})}var r=a.Affix=a.WidgetBase.inherit({klassName:"Affix",init:function(i,e){this.options=t.mixin({},r.DEFAULTS,e),this.$target=o(this.options.target).on("scroll.bs.affix.data-api",t.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",t.proxy(this.checkPositionWithEventLoop,this)),this.$element=o(i),this.affixed=null,this.unpin=null,this.pinnedOffset=null,this.checkPosition()},getState:function(t,i,e,s){var n=this.$target.scrollTop(),f=this.$element.offset(),o=this.$target.height();if(null!=e&&"top"==this.affixed)return n<e&&"top";if("bottom"==this.affixed)return null!=e?!(n+this.unpin<=f.top)&&"bottom":!(n+o<=t-s)&&"bottom";var a=null==this.affixed,h=a?n:f.top,r=a?o:i;return null!=e&&n<=e?"top":null!=s&&h+r>=t-s&&"bottom"},getPinnedOffset:function(){if(this.pinnedOffset)return this.pinnedOffset;this.$element.removeClass(r.RESET).addClass("affix");var t=this.$target.scrollTop(),i=this.$element.offset();return this.pinnedOffset=i.top-t},checkPositionWithEventLoop:function(){setTimeout(t.proxy(this.checkPosition,this),1)},checkPosition:function(){if(this.$element.is(":visible")){var t=this.$element.height(),i=this.options.offset,s=i.top,n=i.bottom,f=Math.max(o(document).height(),o(document.body).height());"object"!=typeof i&&(n=s=i),"function"==typeof s&&(s=i.top(this.$element)),"function"==typeof n&&(n=i.bottom(this.$element));var a=this.getState(f,t,s,n);if(this.affixed!=a){null!=this.unpin&&this.$element.css("top","");var h="affix"+(a?"-"+a:""),l=e.create(h+".bs.affix");if(this.$element.trigger(l),l.isDefaultPrevented())return;this.affixed=a,this.unpin="bottom"==a?this.getPinnedOffset():null,this.$element.removeClass(r.RESET).addClass(h).trigger(h.replace("affix","affixed")+".bs.affix")}"bottom"==a&&this.$element.offset({top:f-t-n})}}});r.VERSION="3.3.7",r.RESET="affix affix-top affix-bottom",r.DEFAULTS={offset:0,target:window};var l=o.fn.affix;return o.fn.affix=h,o.fn.affix.Constructor=r,o.fn.affix.noConflict=function(){return o.fn.affix=l,this},o.fn.affix});
//# sourceMappingURL=sourcemaps/affix.js.map
