/**
 * skylark-bs-swt - The skylark bootstrap standard widget tookit
 * @author Hudaokeji, Inc.
 * @version v0.9.0-beta
 * @link https://github.com/skylarkui/skylark-bs-swt/
 * @license MIT
 */
define(["skylark-utils/langx","skylark-utils/browser","skylark-utils/eventer","skylark-utils/noder","skylark-utils/geom","skylark-utils/velm","skylark-utils/query","./sbswt"],function(t,e,i,s,n,a,o,l){"use strict";function r(t){return this.each(function(){var e=o(this),i=e.data("bs.button"),s="object"==typeof t&&t;i||e.data("bs.button",i=new u(this,s)),"toggle"==t?i.toggle():t&&i.setState(t)})}var u=l.Button=l.WidgetBase.inherit({klassName:"Button",init:function(e,i){var s=this.$element=o(e);this.options=t.mixin({},u.DEFAULTS,i),this.isLoading=!1,s.closest('[data-toggle^="button"]')&&s.on("click.bs.button.data-api",t.proxy(function(t){if(this.toggle(),!o(t.target).is('input[type="radio"], input[type="checkbox"]')){t.preventDefault();var e=this.$element;e.is("input,button")?e.trigger("focus"):e.find("input:visible,button:visible").first().trigger("focus")}},this))},setState:function(e){var i="disabled",s=this.$element,n=s.is("input")?"val":"html",a=s.data();e+="Text",null==a.resetText&&s.data("resetText",s[n]()),setTimeout(t.proxy(function(){s[n](null==a[e]?this.options[e]:a[e]),"loadingText"==e?(this.isLoading=!0,s.addClass(i).attr(i,i).prop(i,!0)):this.isLoading&&(this.isLoading=!1,s.removeClass(i).removeAttr(i).prop(i,!1))},this),0)},toggle:function(){var t=!0,e=this.$element.closest('[data-toggle="buttons"]');if(e.length){var i=this.$element.find("input");"radio"==i.prop("type")?(i.prop("checked")&&(t=!1),e.find(".active").removeClass("active"),this.$element.addClass("active")):"checkbox"==i.prop("type")&&(i.prop("checked")!==this.$element.hasClass("active")&&(t=!1),this.$element.toggleClass("active")),i.prop("checked",this.$element.hasClass("active")),t&&i.trigger("change")}else this.$element.attr("aria-pressed",!this.$element.hasClass("active")),this.$element.toggleClass("active")}});u.VERSION="3.3.7",u.DEFAULTS={loadingText:"loading..."};var c=o.fn.button;return o.fn.button=r,o.fn.button.Constructor=u,o.fn.button.noConflict=function(){return o.fn.button=c,this},o.fn.button});
//# sourceMappingURL=sourcemaps/button.js.map
