/**
 * skylark-bs-swt - The skylark bootstrap standard widget tookit
 * @author Hudaokeji, Inc.
 * @version v0.9.0-beta
 * @link https://github.com/skylarkui/skylark-bs-swt/
 * @license MIT
 */
define(["skylark-utils/langx","skylark-utils/browser","skylark-utils/eventer","skylark-utils/noder","skylark-utils/geom","skylark-utils/velm","skylark-utils/query","./sbswt"],function(e,t,i,c,s,o,h,a){var n=h.fn.checkbox,r=function(e){window&&window.console&&window.console.error&&window.console.error(e)},l=a.Checkbox=a.WidgetBase.inherit({klassName:"Checkbox",init:function(t,i){this.options=e.mixin({},h.fn.checkbox.defaults,i);var c=h(t);if("label"!==t.tagName.toLowerCase())return void r("Checkbox must be initialized on the `label` that wraps the `input` element. See https://github.com/ExactTarget/fuelux/blob/master/reference/markup/checkbox.html for example of proper markup. Call `.checkbox()` on the `<label>` not the `<input>`");this.$label=c,this.$chk=this.$label.find('input[type="checkbox"]'),this.$container=c.parent(".checkbox"),!this.options.ignoreVisibilityCheck&&this.$chk.css("visibility").match(/hidden|collapse/)&&r("For accessibility reasons, in order for tab and space to function on checkbox, checkbox `<input />`'s `visibility` must not be set to `hidden` or `collapse`. See https://github.com/ExactTarget/fuelux/pull/1996 for more details.");var s=this.$chk.attr("data-toggle");this.$toggleContainer=h(s),this.$chk.on("change",e.proxy(this.itemchecked,this)),this.setInitialState()},setInitialState:function(){var e=this.$chk,t=e.prop("checked"),i=e.prop("disabled");this.setCheckedState(e,t),this.setDisabledState(e,i)},setCheckedState:function(e,t){var i=e,c=this.$label,s=this.$toggleContainer;t?(i.prop("checked",!0),c.addClass("checked"),s.removeClass("hide hidden"),c.trigger("checked.fu.checkbox")):(i.prop("checked",!1),c.removeClass("checked"),s.addClass("hidden"),c.trigger("unchecked.fu.checkbox")),c.trigger("changed.fu.checkbox",t)},setDisabledState:function(e,t){var i=h(e),c=this.$label;return t?(i.prop("disabled",!0),c.addClass("disabled"),c.trigger("disabled.fu.checkbox")):(i.prop("disabled",!1),c.removeClass("disabled"),c.trigger("enabled.fu.checkbox")),i},itemchecked:function(e){var t=h(e.target),i=t.prop("checked");this.setCheckedState(t,i)},toggle:function(){var e=this.isChecked();e?this.uncheck():this.check()},check:function(){this.setCheckedState(this.$chk,!0)},uncheck:function(){this.setCheckedState(this.$chk,!1)},isChecked:function(){var e=this.$chk.prop("checked");return e},enable:function(){this.setDisabledState(this.$chk,!1)},disable:function(){this.setDisabledState(this.$chk,!0)},destroy:function(){return this.$label.remove(),this.$label[0].outerHTML}});return l.prototype.getValue=l.prototype.isChecked,h.fn.checkbox=function(e){var t,i=Array.prototype.slice.call(arguments,1),c=this.each(function(){var c=h(this),s=c.data("fu.checkbox"),o="object"==typeof e&&e;s||c.data("fu.checkbox",s=new l(this,o)),"string"==typeof e&&(t=s[e].apply(s,i))});return void 0===t?c:t},h.fn.checkbox.defaults={ignoreVisibilityCheck:!1},h.fn.checkbox.Constructor=l,h.fn.checkbox.noConflict=function(){return h.fn.checkbox=n,this},h.fn.checkbox});
//# sourceMappingURL=sourcemaps/checkbox.js.map
