/**
 * skylark-bs-swt - The skylark bootstrap standard widget tookit
 * @author Hudaokeji, Inc.
 * @version v0.9.0-beta
 * @link https://github.com/skylarkui/skylark-bs-swt/
 * @license MIT
 */
define(["skylark-utils/langx","skylark-utils/browser","skylark-utils/eventer","skylark-utils/noder","skylark-utils/geom","skylark-utils/velm","skylark-utils/query"],function(t,e,n,i,l,o,s){var r=s.fn.infinitescroll,c=function(e,n){this.$element=s(e),this.$element.addClass("infinitescroll"),this.options=t.mixin({},s.fn.infinitescroll.defaults,n),this.curScrollTop=this.$element.scrollTop(),this.curPercentage=this.getPercentage(),this.fetchingData=!1,this.$element.on("scroll.fu.infinitescroll",t.proxy(this.onScroll,this)),this.onScroll()};c.prototype={constructor:c,destroy:function(){return this.$element.remove(),this.$element.empty(),this.$element[0].outerHTML},disable:function(){this.$element.off("scroll.fu.infinitescroll")},enable:function(){this.$element.on("scroll.fu.infinitescroll",t.proxy(this.onScroll,this))},end:function(t){var e=s('<div class="infinitescroll-end"></div>');t?e.append(t):e.append("---------"),this.$element.append(e),this.disable()},getPercentage:function(){var t="border-box"===this.$element.css("box-sizing")?this.$element.outerHeight():this.$element.height(),e=this.$element.get(0).scrollHeight;return e>t?t/(e-this.curScrollTop)*100:0},fetchData:function(t){var e,n=s('<div class="infinitescroll-load"></div>'),i=this,l=function(){var t={percentage:i.curPercentage,scrollTop:i.curScrollTop},e=s('<div class="loader"></div>');n.append(e),e.loader(),i.options.dataSource&&i.options.dataSource(t,function(t){var e;n.remove(),t.content&&i.$element.append(t.content),t.end&&(e=t.end!==!0?t.end:void 0,i.end(e)),i.fetchingData=!1})};this.fetchingData=!0,this.$element.append(n),this.options.hybrid&&t!==!0?(e=s('<button type="button" class="btn btn-primary"></button>'),"object"==typeof this.options.hybrid?e.append(this.options.hybrid.label):e.append('<span class="glyphicon glyphicon-repeat"></span>'),e.on("click.fu.infinitescroll",function(){e.remove(),l()}),n.append(e)):l()},onScroll:function(t){this.curScrollTop=this.$element.scrollTop(),this.curPercentage=this.getPercentage(),!this.fetchingData&&this.curPercentage>=this.options.percentage&&this.fetchData()}},s.fn.infinitescroll=function(t){var e,n=Array.prototype.slice.call(arguments,1),i=this.each(function(){var i=s(this),l=i.data("fu.infinitescroll"),o="object"==typeof t&&t;l||i.data("fu.infinitescroll",l=new c(this,o)),"string"==typeof t&&(e=l[t].apply(l,n))});return void 0===e?i:e},s.fn.infinitescroll.defaults={dataSource:null,hybrid:!1,percentage:95},s.fn.infinitescroll.Constructor=c,s.fn.infinitescroll.noConflict=function(){return s.fn.infinitescroll=r,this}});
//# sourceMappingURL=sourcemaps/infinite-scroll.js.map
