/**
 * skylark-bs-swt - The skylark bootstrap standard widget tookit
 * @author Hudaokeji, Inc.
 * @version v0.9.0-beta
 * @link https://github.com/skylarkui/skylark-bs-swt/
 * @license MIT
 */
define(["skylark-utils/langx","skylark-utils/browser","skylark-utils/eventer","skylark-utils/noder","skylark-utils/geom","skylark-utils/velm","skylark-utils/query","./sbswt"],function(t,a,e,n,i,s,r,l){"use strict";function d(t){return this.each(function(){var a=r(this),e=a.data("bs.tab");e||a.data("bs.tab",e=new o(this)),"string"==typeof t&&e[t]()})}var o=l.Tab=l.WidgetBase.inherit({klassName:"Tab",init:function(a,e){this.element=r(a),this.element.on("click.bs.tab.data-api",t.proxy(function(t){t.preventDefault(),this.show()},this))},show:function(){var t=this.element,a=t.closest("ul:not(.dropdown-menu)"),n=t.data("target");if(n||(n=t.attr("href"),n=n&&n.replace(/.*(?=#[^\s]*$)/,"")),!t.parent("li").hasClass("active")){var i=a.find(".active:last a"),s=e.create("hide.bs.tab",{relatedTarget:t[0]}),l=e.create("show.bs.tab",{relatedTarget:i[0]});if(i.trigger(s),t.trigger(l),!l.isDefaultPrevented()&&!s.isDefaultPrevented()){var d=r(n);this.activate(t.closest("li"),a),this.activate(d,d.parent(),function(){i.trigger({type:"hidden.bs.tab",relatedTarget:t[0]}),t.trigger({type:"shown.bs.tab",relatedTarget:i[0]})})}}},activate:function(t,e,n){function i(){s.removeClass("active").find("> .dropdown-menu > .active").removeClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!1),t.addClass("active").find('[data-toggle="tab"]').attr("aria-expanded",!0),r?(t[0].offsetWidth,t.addClass("in")):t.removeClass("fade"),t.parent(".dropdown-menu").length&&t.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!0),n&&n()}var s=e.find("> .active"),r=n&&a.support.transition&&(s.length&&s.hasClass("fade")||!!e.find("> .fade").length);s.length&&r?s.one("bsTransitionEnd",i).emulateTransitionEnd(o.TRANSITION_DURATION):i(),s.removeClass("in")}});o.VERSION="3.3.7",o.TRANSITION_DURATION=150;var f=r.fn.tab;r.fn.tab=d,r.fn.tab.Constructor=o,r.fn.tab.noConflict=function(){return r.fn.tab=f,this}});
//# sourceMappingURL=sourcemaps/tab.js.map
