/**
 * skylark-bs-swt - The skylark bootstrap standard widget tookit
 * @author Hudaokeji, Inc.
 * @version v0.9.0-beta
 * @link https://github.com/skylarkui/skylark-bs-swt/
 * @license MIT
 */
define(["skylark-utils/langx","skylark-utils/browser","skylark-utils/eventer","skylark-utils/noder","skylark-utils/geom","skylark-utils/velm","skylark-utils/query","./sbswt"],function(t,n,e,a,i,o,s,p){var r=p.Toolbar=p.WidgetBase.inherit({klassName:"Toolbar",init:function(n,e){this._options=t.mixin({autoredraw:!0,buttons:{},context:{},list:[],show:!0},e),this.$container=s('<nav class="navbar"/>'),this.$el=s(n).append(this.$container),this.$container.on("mousedown.bs.dropdown.data-api",'[data-toggle="dropdown"]',function(t){s(this).dropdown()}),this.render()},render:function(){function n(n,s){t.each(n,function(t,n){var p=n.type;switch(p||(p="button"),p){case"buttongroup":e(n,s);break;case"button":a(n,s);break;case"dropdown":case"dropup":i(n,s);break;case"input":o(n,s);break;default:throw"Wrong widget button type"}})}function e(t,e){var a=s("<div/>",{"class":"btn-group",role:"group"});return e.append(a),n(t.items,a),a}function a(n,e){var a=s('<button type="button" class="btn btn-default"/>'),i=t.mixin({},n);"icon"in n&&(a.append(s("<span/>",{"class":n.icon})),delete i.icon),"text"in i&&(a.append(" "+n.text),delete i.text),a.attr(i),e.append(a)}function i(n,e){var a=s('<div class="btn-group" role="group"/>'),i=s('<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"/>'),o=s('<ul class="dropdown-menu"/>'),p=t.mixin({},n);"dropup"===n.type&&a.addClass("dropup"),"icon"in n&&(i.append(s("<span/>",{"class":n.icon})),delete p.icon),"text"in n&&(i.append(" "+n.text),delete p.text),i.append(' <span class="caret"/>');for(var r in n.list){var d=n.list[r],u=s("<li/>");"icon"in d&&u.append(s("<span/>",{"class":d.icon})),"text"in d&&u.append(" "+d.text),u.attr(d),o.append(u)}a.attr(p),a.append(i),a.append(o),e.append(a)}function o(n,e){var a=s('<div class="input-group"/>'),i=s('<input class="form-control"/>'),o=t.mixin({},n);if("prefix"in n){var p=s('<span class="input-group-addon"/>');p.html(n.prefix),a.append(p),delete o.prefix}if(a.append(i),"sufix"in n){var r=s('<span class="input-group-addon"/>');r.html(n.sufix),a.append(r),delete o.sufix}o.type=o.inputType,delete o.inputType,i.attr(o),e.append(a)}var p=this._options.items;p&&n(p,this.$container)}});return s.fn.toolbar=function(n){return n=n||{},this.each(function(){return new r(this,t.mixin({},n,!0))})},r});
//# sourceMappingURL=sourcemaps/toolbar.js.map
